-- Populate airports table with comprehensive real airport data
INSERT INTO airports (id, code, name, city, country, latitude, longitude, timezone, is_hub, is_active) VALUES
-- Major International Hubs (Priority 1)
(gen_random_uuid(), 'ATL', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta', 'United States', 33.6407, -84.4277, 'America/New_York', true, true),
(gen_random_uuid(), 'DXB', 'Dubai International Airport', 'Dubai', 'United Arab Emirates', 25.2532, 55.3657, 'Asia/Dubai', true, true),
(gen_random_uuid(), 'LHR', 'London Heathrow Airport', 'London', 'United Kingdom', 51.4700, -0.4543, 'Europe/London', true, true),
(gen_random_uuid(), 'LAX', 'Los Angeles International Airport', 'Los Angeles', 'United States', 33.9425, -118.4081, 'America/Los_Angeles', true, true),
(gen_random_uuid(), 'ORD', 'Chicago O''Hare International Airport', 'Chicago', 'United States', 41.9742, -87.9073, 'America/Chicago', true, true),
(gen_random_uuid(), 'CDG', 'Charles de Gaulle Airport', 'Paris', 'France', 49.0097, 2.5479, 'Europe/Paris', true, true),
(gen_random_uuid(), 'FRA', 'Frankfurt Airport', 'Frankfurt', 'Germany', 50.0379, 8.5622, 'Europe/Berlin', true, true),
(gen_random_uuid(), 'AMS', 'Amsterdam Airport Schiphol', 'Amsterdam', 'Netherlands', 52.3105, 4.7683, 'Europe/Amsterdam', true, true),
(gen_random_uuid(), 'IST', 'Istanbul Airport', 'Istanbul', 'Turkey', 41.2753, 28.7519, 'Europe/Istanbul', true, true),
(gen_random_uuid(), 'DOH', 'Hamad International Airport', 'Doha', 'Qatar', 25.2731, 51.6080, 'Asia/Qatar', true, true),
(gen_random_uuid(), 'SIN', 'Singapore Changi Airport', 'Singapore', 'Singapore', 1.3644, 103.9915, 'Asia/Singapore', true, true),
(gen_random_uuid(), 'ICN', 'Incheon International Airport', 'Seoul', 'South Korea', 37.4602, 126.4407, 'Asia/Seoul', true, true),
(gen_random_uuid(), 'NRT', 'Narita International Airport', 'Tokyo', 'Japan', 35.7720, 140.3929, 'Asia/Tokyo', true, true),
(gen_random_uuid(), 'HND', 'Tokyo Haneda Airport', 'Tokyo', 'Japan', 35.5494, 139.7798, 'Asia/Tokyo', true, true),
(gen_random_uuid(), 'PEK', 'Beijing Capital International Airport', 'Beijing', 'China', 40.0799, 116.6031, 'Asia/Shanghai', true, true),

-- Regional Hubs (Priority 2)
(gen_random_uuid(), 'JFK', 'John F. Kennedy International Airport', 'New York', 'United States', 40.6413, -73.7781, 'America/New_York', false, true),
(gen_random_uuid(), 'LGW', 'London Gatwick Airport', 'London', 'United Kingdom', 51.1537, -0.1821, 'Europe/London', false, true),
(gen_random_uuid(), 'FCO', 'Leonardo da Vinci International Airport', 'Rome', 'Italy', 41.8003, 12.2389, 'Europe/Rome', false, true),
(gen_random_uuid(), 'MAD', 'Adolfo Suárez Madrid–Barajas Airport', 'Madrid', 'Spain', 40.4839, -3.5680, 'Europe/Madrid', false, true),
(gen_random_uuid(), 'BCN', 'Barcelona-El Prat Airport', 'Barcelona', 'Spain', 41.2974, 2.0833, 'Europe/Madrid', false, true),
(gen_random_uuid(), 'MUC', 'Munich Airport', 'Munich', 'Germany', 48.3537, 11.7750, 'Europe/Berlin', false, true),
(gen_random_uuid(), 'ZUR', 'Zurich Airport', 'Zurich', 'Switzerland', 47.4647, 8.5492, 'Europe/Zurich', false, true),
(gen_random_uuid(), 'VIE', 'Vienna International Airport', 'Vienna', 'Austria', 48.1103, 16.5697, 'Europe/Vienna', false, true),
(gen_random_uuid(), 'CPH', 'Copenhagen Airport', 'Copenhagen', 'Denmark', 55.6181, 12.6561, 'Europe/Copenhagen', false, true),
(gen_random_uuid(), 'ARN', 'Stockholm Arlanda Airport', 'Stockholm', 'Sweden', 59.6519, 17.9186, 'Europe/Stockholm', false, true),
(gen_random_uuid(), 'OSL', 'Oslo Airport', 'Oslo', 'Norway', 60.1939, 11.1004, 'Europe/Oslo', false, true),
(gen_random_uuid(), 'HEL', 'Helsinki Airport', 'Helsinki', 'Finland', 60.3172, 24.9633, 'Europe/Helsinki', false, true),
(gen_random_uuid(), 'KEF', 'Keflavík International Airport', 'Reykjavik', 'Iceland', 63.9850, -22.6056, 'Atlantic/Reykjavik', false, true),
(gen_random_uuid(), 'YYZ', 'Toronto Pearson International Airport', 'Toronto', 'Canada', 43.6777, -79.6248, 'America/Toronto', false, true),
(gen_random_uuid(), 'YVR', 'Vancouver International Airport', 'Vancouver', 'Canada', 49.1967, -123.1815, 'America/Vancouver', false, true),

-- Standard Airports (Priority 3)
(gen_random_uuid(), 'SFO', 'San Francisco International Airport', 'San Francisco', 'United States', 37.6213, -122.3790, 'America/Los_Angeles', false, true),
(gen_random_uuid(), 'MIA', 'Miami International Airport', 'Miami', 'United States', 25.7959, -80.2870, 'America/New_York', false, true),
(gen_random_uuid(), 'DEN', 'Denver International Airport', 'Denver', 'United States', 39.8561, -104.6737, 'America/Denver', false, true),
(gen_random_uuid(), 'SEA', 'Seattle-Tacoma International Airport', 'Seattle', 'United States', 47.4502, -122.3088, 'America/Los_Angeles', false, true),
(gen_random_uuid(), 'BOS', 'Logan International Airport', 'Boston', 'United States', 42.3656, -71.0096, 'America/New_York', false, true),
(gen_random_uuid(), 'LAS', 'McCarran International Airport', 'Las Vegas', 'United States', 36.0840, -115.1537, 'America/Los_Angeles', false, true),
(gen_random_uuid(), 'PHX', 'Phoenix Sky Harbor International Airport', 'Phoenix', 'United States', 33.4484, -112.0740, 'America/Phoenix', false, true),
(gen_random_uuid(), 'IAH', 'George Bush Intercontinental Airport', 'Houston', 'United States', 29.9902, -95.3368, 'America/Chicago', false, true),
(gen_random_uuid(), 'DFW', 'Dallas/Fort Worth International Airport', 'Dallas', 'United States', 32.8998, -97.0403, 'America/Chicago', false, true),
(gen_random_uuid(), 'MSP', 'Minneapolis-Saint Paul International Airport', 'Minneapolis', 'United States', 44.8848, -93.2223, 'America/Chicago', false, true),
(gen_random_uuid(), 'DTW', 'Detroit Metropolitan Wayne County Airport', 'Detroit', 'United States', 42.2162, -83.3554, 'America/New_York', false, true),
(gen_random_uuid(), 'CLT', 'Charlotte Douglas International Airport', 'Charlotte', 'United States', 35.2144, -80.9473, 'America/New_York', false, true),
(gen_random_uuid(), 'PHL', 'Philadelphia International Airport', 'Philadelphia', 'United States', 39.8744, -75.2424, 'America/New_York', false, true),
(gen_random_uuid(), 'BWI', 'Baltimore/Washington International Airport', 'Baltimore', 'United States', 39.1774, -76.6684, 'America/New_York', false, true),
(gen_random_uuid(), 'DCA', 'Ronald Reagan Washington National Airport', 'Washington', 'United States', 38.8521, -77.0377, 'America/New_York', false, true),

-- International Destinations
(gen_random_uuid(), 'SYD', 'Sydney Kingsford Smith Airport', 'Sydney', 'Australia', -33.9399, 151.1753, 'Australia/Sydney', false, true),
(gen_random_uuid(), 'MEL', 'Melbourne Airport', 'Melbourne', 'Australia', -37.6690, 144.8410, 'Australia/Melbourne', false, true),
(gen_random_uuid(), 'BKK', 'Suvarnabhumi Airport', 'Bangkok', 'Thailand', 13.6900, 100.7501, 'Asia/Bangkok', false, true),
(gen_random_uuid(), 'KUL', 'Kuala Lumpur International Airport', 'Kuala Lumpur', 'Malaysia', 2.7456, 101.7072, 'Asia/Kuala_Lumpur', false, true),
(gen_random_uuid(), 'CGK', 'Soekarno-Hatta International Airport', 'Jakarta', 'Indonesia', -6.1275, 106.6537, 'Asia/Jakarta', false, true),
(gen_random_uuid(), 'MNL', 'Ninoy Aquino International Airport', 'Manila', 'Philippines', 14.5086, 121.0194, 'Asia/Manila', false, true),
(gen_random_uuid(), 'HKG', 'Hong Kong International Airport', 'Hong Kong', 'Hong Kong', 22.3080, 113.9185, 'Asia/Hong_Kong', false, true),
(gen_random_uuid(), 'TPE', 'Taiwan Taoyuan International Airport', 'Taipei', 'Taiwan', 25.0797, 121.2342, 'Asia/Taipei', false, true),
(gen_random_uuid(), 'BOM', 'Chhatrapati Shivaji Maharaj International Airport', 'Mumbai', 'India', 19.0896, 72.8656, 'Asia/Kolkata', false, true),
(gen_random_uuid(), 'DEL', 'Indira Gandhi International Airport', 'New Delhi', 'India', 28.5562, 77.1000, 'Asia/Kolkata', false, true),
(gen_random_uuid(), 'BLR', 'Kempegowda International Airport', 'Bangalore', 'India', 13.1979, 77.7063, 'Asia/Kolkata', false, true),
(gen_random_uuid(), 'GRU', 'São Paulo/Guarulhos International Airport', 'São Paulo', 'Brazil', -23.4356, -46.4731, 'America/Sao_Paulo', false, true),
(gen_random_uuid(), 'GIG', 'Rio de Janeiro/Galeão International Airport', 'Rio de Janeiro', 'Brazil', -22.8099, -43.2505, 'America/Sao_Paulo', false, true),
(gen_random_uuid(), 'EZE', 'Ezeiza International Airport', 'Buenos Aires', 'Argentina', -34.8222, -58.5358, 'America/Argentina/Buenos_Aires', false, true),
(gen_random_uuid(), 'SCL', 'Santiago International Airport', 'Santiago', 'Chile', -33.3930, -70.7858, 'America/Santiago', false, true),
(gen_random_uuid(), 'LIM', 'Jorge Chávez International Airport', 'Lima', 'Peru', -12.0219, -77.1143, 'America/Lima', false, true),
(gen_random_uuid(), 'BOG', 'El Dorado International Airport', 'Bogotá', 'Colombia', 4.7016, -74.1469, 'America/Bogota', false, true),
(gen_random_uuid(), 'MEX', 'Mexico City International Airport', 'Mexico City', 'Mexico', 19.4363, -99.0721, 'America/Mexico_City', false, true),
(gen_random_uuid(), 'CUN', 'Cancún International Airport', 'Cancún', 'Mexico', 21.0365, -86.8770, 'America/Cancun', false, true),
(gen_random_uuid(), 'JNB', 'O.R. Tambo International Airport', 'Johannesburg', 'South Africa', -26.1367, 28.2411, 'Africa/Johannesburg', false, true),
(gen_random_uuid(), 'CPT', 'Cape Town International Airport', 'Cape Town', 'South Africa', -33.9715, 18.6021, 'Africa/Johannesburg', false, true),
(gen_random_uuid(), 'CAI', 'Cairo International Airport', 'Cairo', 'Egypt', 30.1219, 31.4056, 'Africa/Cairo', false, true),
(gen_random_uuid(), 'ADD', 'Addis Ababa Bole International Airport', 'Addis Ababa', 'Ethiopia', 8.9806, 38.7997, 'Africa/Addis_Ababa', false, true),
(gen_random_uuid(), 'NBO', 'Jomo Kenyatta International Airport', 'Nairobi', 'Kenya', -1.3192, 36.9278, 'Africa/Nairobi', false, true),
(gen_random_uuid(), 'LOS', 'Murtala Muhammed International Airport', 'Lagos', 'Nigeria', 6.5774, 3.3212, 'Africa/Lagos', false, true);

-- Update table statistics
ANALYZE airports;
